import "./globals.css";
import { Providers } from "./providers";
import ThemeSwitch from "./ThemeSwitcher";
export const metadata = {
  title: "Chula ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head></head>
      <body id="__next">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
